// wp-content/plugins/gp-populate-anything/js/src/components/Filter.tsx
import useGPPAStore from '../store/store';
import truncateStringMiddle from '../helpers/truncateStringMiddle';
import Select from './Select';
import useDeepCompareEffect from 'use-deep-compare-effect';

const { strings, defaultOperators } = window.GPPA_ADMIN;

const useFilterOperators = ({
	filter,
	flattenedProperties,
	objectTypeInstance,
}: {
	filter: GPPAFilter;
	flattenedProperties: { [property: string]: GPPAProperty };
	objectTypeInstance: GPPAObjectType | null;
}): string[] => {
	/* Labels for operators are pulled from i18nStrings in the Vue bindings */
	if (filter.property in flattenedProperties && objectTypeInstance) {
		const property = flattenedProperties[filter.property];

		if (property.operators?.length) {
			return property.operators;
		}

		if ('group' in property && property.group) {
			const group = objectTypeInstance.groups[property.group];

			if (group.operators?.length) {
				return group.operators;
			}
		}
	}

	return defaultOperators;
};

const Filter = ({
	index,
	groupIndex,
	filter,
	populate,
	filters,
}: {
	index: number;
	groupIndex: number;
	filter: GPPAFilter;
	filters: GPPAFilter[];
	populate: GPPAPopulate;
}) => {
	const useStore = useGPPAStore(populate);
	const fieldId = useStore((state) => state.field?.id);
	const propertiesLoaded = useStore(
		(state) => state.computed.propertiesLoaded
	);
	const flattenedProperties = useStore(
		(state) => state.computed.flattenedProperties
	);
	const objectTypeInstance = useStore(
		(state) => state.computed.objectTypeInstance
	);
	const filterPropertiesUngrouped = useStore(
		(state) => state.computed.filterPropertiesUngrouped
	);
	const filterPropertiesGrouped = useStore(
		(state) => state.computed.filterPropertiesGrouped
	);
	const filterSpecialValues = useStore(
		(state) => state.computed.filterSpecialValues
	);
	const filterFormFieldValues = useStore(
		(state) => state.computed.filterFormFieldValues
	);
	const propertyValues = useStore((state) => state.propertyValues);
	const getPropertyValues = useStore((state) => state.getPropertyValues);
	const updateFilter = useStore((state) => state.updateFilter);
	const addFilter = useStore((state) => state.addFilter);
	const removeFilter = useStore((state) => state.removeFilter);

	const propertyValuesLoaded = filter.property in propertyValues;

	const operators = useFilterOperators({
		filter,
		flattenedProperties,
		objectTypeInstance,
	});

	// If filter.property is not set, set it to the first property
	useDeepCompareEffect(() => {
		if (!filter.property) {
			let property = '';

			// Get the first from either ungrouped or grouped properties. First, try ungrouped.
			if (filterPropertiesUngrouped?.length) {
				property = filterPropertiesUngrouped[0].value;
			} else {
				const firstGroup = Object.values(filterPropertiesGrouped)[0];
				if (firstGroup?.length) {
					property = firstGroup[0].value;
				}
			}

			updateFilter(groupIndex, index, {
				property,
			});
		}
	}, [
		filter.property,
		filterPropertiesUngrouped,
		filterPropertiesGrouped,
		groupIndex,
		index,
		updateFilter,
	]);

	useDeepCompareEffect(() => {
		getPropertyValues(filter.property);
	}, [getPropertyValues, filter.property, fieldId]);

	if (!objectTypeInstance) {
		return null;
	}

	return (
		<div
			className="gppa-filter"
			aria-label={strings.filterAriaLabel.gformFormat(index + 1)}
			role="group"
		>
			<select
				disabled={!propertiesLoaded}
				className="gppa-filter-property"
				value={propertiesLoaded ? filter.property : ''}
				onChange={(event) =>
					updateFilter(groupIndex, index, {
						property: event.target.value,
						value: '',
					})
				}
			>
				{!propertiesLoaded || !objectTypeInstance ? (
					<option value="" disabled hidden>
						{strings.loadingEllipsis}
					</option>
				) : (
					<>
						{filterPropertiesUngrouped?.map((option) => (
							<option value={option.value} key={option.value}>
								{truncateStringMiddle(option.label)}
							</option>
						))}

						{Object.entries(filterPropertiesGrouped).map(
							([groupID, options]) => (
								<optgroup
									key={groupID}
									label={
										groupID in objectTypeInstance.groups
											? objectTypeInstance.groups[groupID]
													.label
											: undefined
									}
								>
									{options.map((option) => (
										<option
											value={option.value}
											key={option.value}
										>
											{truncateStringMiddle(option.label)}
										</option>
									))}
								</optgroup>
							)
						)}
					</>
				)}
			</select>

			<select
				className="gppa-filter-operator"
				value={filter.operator}
				onChange={(event) =>
					updateFilter(groupIndex, index, {
						operator: event.target.value,
					})
				}
				disabled={!propertiesLoaded || !propertyValuesLoaded}
			>
				{operators.map((operator) => (
					<option value={operator} key={operator}>
						{/* @ts-ignore */}
						{strings.operators[operator]}
					</option>
				))}
			</select>

			<Select
				className="gppa-filter-value"
				value={
					propertiesLoaded && propertyValuesLoaded ? filter.value : ''
				}
				objectTypeInstance={objectTypeInstance}
				flattenedProperties={flattenedProperties}
				forceCustomInput={filter.operator.indexOf('like') !== -1}
				disabled={!propertiesLoaded || !propertyValuesLoaded}
				onChange={(value) => updateFilter(groupIndex, index, { value })}
			>
				{!(propertiesLoaded && propertyValuesLoaded) && (
					<option value="" disabled hidden>
						{strings.loadingEllipsis}
					</option>
				)}
				{!filter.value && (
					<option value="" disabled hidden>
						&ndash; Value &ndash;
					</option>
				)}

				<optgroup label={strings.specialValues}>
					<option value="gf_custom">{strings.addCustomValue}</option>

					{filterSpecialValues.map((option, optionIndex) => (
						<option key={option.value} value={option.value}>
							{option.label}
						</option>
					))}
				</optgroup>

				{filterFormFieldValues && filterFormFieldValues.length && (
					<optgroup label={strings.formFieldValues}>
						{filterFormFieldValues.map((option, optionIndex) => (
							<option key={option.value} value={option.value}>
								{truncateStringMiddle(option.label)}
							</option>
						))}
					</optgroup>
				)}

				{propertyValues?.[filter.property] &&
					propertyValues[filter.property].map(
						(option, optionIndex) => (
							<option
								key={option.value}
								value={option.value}
								disabled={option.disabled}
							>
								{truncateStringMiddle(option.label)}
							</option>
						)
					)}
			</Select>

			<div className="repeater-buttons">
				<button
					className="add-item gform-st-icon gform-st-icon--circle-plus"
					title={strings.addFilter}
					onClick={() => addFilter(index, groupIndex)}
				/>
				<button
					className="remove-item gform-st-icon gform-st-icon--circle-minus"
					title={strings.removeFilter}
					onClick={() => removeFilter(index, groupIndex)}
					aria-label={strings.removeFilterAriaLabel.gformFormat(
						index + 1
					)}
				/>
			</div>

			{filters.length > 1 && index !== filters.length - 1 && (
				<div className="gppa-filter-and" aria-label={strings.and}>
					{strings.and}
				</div>
			)}
		</div>
	);
};

export default Filter;

// wp-content/plugins/gp-populate-anything/js/src/components/Filter.vue
<template>
	<div class="gppa-filter" :aria-label="i18nStrings.filterAriaLabel.format( index + 1 )" aria-role="group">
		<select :disabled="loadingProperties"
				class="gppa-filter-property"
				v-model="filterPropertyModel"
				@change="resetFilter"
				ref="propertySelect">
			<option v-if="loadingProperties" value="" selected disabled hidden>{{ i18nStrings.loadingEllipsis }}</option>

			<option v-for="option in filterPropertiesUngrouped" v-bind:value="option.value">
				{{ truncateStringMiddle(option.label) }}
			</option>

			<optgroup v-for="(options, groupID) in filterPropertiesGrouped"
					  v-bind:label="groupID in objectTypeInstance.groups && objectTypeInstance.groups[groupID].label">
				<option v-for="option in options" v-bind:value="option.value">
					{{ truncateStringMiddle(option.label) }}
				</option>
			</optgroup>
		</select>

		<select class="gppa-filter-operator" v-model="filter.operator"
				:disabled="!Object.keys(properties).length || (Object.keys(properties).length === 1 && 'primary-property' in properties) || !(filter.property in propertyValues)">
			<option v-for="operator in operators" v-bind:value="operator">{{ i18nStrings.operators[operator]
				}}
			</option>
		</select>

		<gppa-select-with-custom
			 :loading="loadingPropertyValues"
			 additional-class="gppa-filter-value"
			 v-model="filter.value"
			 :operator="filter.operator"
			 :object-type-instance="objectTypeInstance"
			 :flattened-properties="flattenedProperties">
			<option v-if="!filter.value" value="" disabled selected="selected" hidden>&ndash; Value &ndash;</option>

			<optgroup :label="i18nStrings.specialValues">
				<option value="gf_custom">{{ i18nStrings.addCustomValue }}</option>

				<option v-for="(option, optionIndex) in specialValues"
						v-bind:value="option.value"
						:selected="option.value == filter.value">
					{{ option.label }}
				</option>
			</optgroup>

			<optgroup :label="i18nStrings.formFieldValues" v-if="formFieldValues && formFieldValues.length">
				<option v-for="(option, optionIndex) in formFieldValues"
						v-bind:value="option.value"
						:selected="option.value == filter.value">
					{{ truncateStringMiddle(option.label) }}
				</option>
			</optgroup>

			<option v-for="(option, optionIndex) in propertyValues[filter.property]"
					v-bind:value="option.value"
					v-bind:disabled="option.disabled"
					:selected="option.value == filter.value">
				{{ truncateStringMiddle(option.label) }}
			</option>
		</gppa-select-with-custom>

		<div class="repeater-buttons">
			<button class="add-item gform-st-icon gform-st-icon--circle-plus" @click="$emit('add-filter')" :title="i18nStrings.addFilter" />
			<button class="remove-item gform-st-icon gform-st-icon--circle-minus" @click="$emit('remove-filter')" :title="i18nStrings.removeFilter" :aria-label="i18nStrings.removeFilterAriaLabel.format( index + 1 )" />
		</div>

		<div
			v-if="filters.length > 1 && index !== filters.length - 1"
			class="gppa-filter-and" :aria-label="i18nStrings.and">
			{{ i18nStrings.and }}
		</div>
	</div>
</template>

<script lang="ts">
	import Vue from 'vue';
	import truncateStringMiddle from '../helpers/truncateStringMiddle';
	import SelectWithCustom from './SelectWithCustom.vue';

	export default Vue.extend({
		props: [
			'filter',
			'filters',
			'index',
			'field',
			'properties',
			'flattenedProperties',
			'propertyValues',
			'ungroupedProperties',
			'groupedProperties',
			'objectTypeInstance',
			'getPropertyValues',
		],
		components: {
			'gppa-select-with-custom': SelectWithCustom,
		},
		mounted() {
			// @ts-ignore
			this.$refs.propertySelect?.focus();
		},
		created: function () {
			if (this.filter.property) {
				return this.getPropertyValues(this.filter.property);
			}

			this.filter.property = (Object.values(this.flattenedProperties) as any)[0].value;
		},
		data: function () {
			return {
				i18nStrings: window.GPPA_ADMIN.strings,
				defaultOperator: 'is',
			}
		},
		watch: {
			'filter.property': function (val, oldVal) {
				this.getPropertyValues(val);
			}
		},
		methods: {
			truncateStringMiddle: truncateStringMiddle,
			/**
			 * resetFilter's contents were originally extracted from the 'filter.property' watcher to prevent the
			 * filter value from needlessly resetting to having no value when the field itself changes.
			 */
			resetFilter: function() {
				this.filter.value = '';
				this.filter.operator = this.defaultOperator;
			}
		},
		computed: {
			/* Used so we can set it to an empty value while loading. */
			filterPropertyModel: {
				get() {
					if (this.loadingProperties) {
						return '';
					}

					return this.filter.property;
				},
				set(val) {
					this.filter.property = val;
				}
			},
			loadingProperties: function() {
				return !Object.keys(this.properties).length || (Object.keys(this.properties).length === 1 && 'primary-property' in this.properties);
			},
			loadingPropertyValues: function() {
				return !(this.filter.property in this.propertyValues);
			},
			specialValues: function () {
				const specialValues = [
					{
						label: 'Current User ID',
						value: 'special_value:current_user:ID',
					},
					{
						label: 'Current Post ID',
						value: 'special_value:current_post:ID',
					}
				];

				if (this.objectTypeInstance?.supportsNullFilterValue) {
					specialValues.push({
						label: 'NULL',
						value: 'special_value:null',
					});
				}

				return specialValues;
			},
			formFieldValues: function () {

				var formFieldValues = [];

				const excludedFormFieldValueInputTypes = ['chainedselect'];

				for (var i = 0; i < window.form.fields.length; i++) {

					const field = window.form.fields[i];
					const inputType = window.GetInputType(field);

					if (excludedFormFieldValueInputTypes.includes(inputType)) {
						continue;
					}

					if (window.IsConditionalLogicField(field) || ['date'].includes(inputType)) {

						if (field.inputs && !['checkbox', 'email'].includes(inputType)) {
							for (var j = 0; j < field.inputs.length; j++) {
								var input = field.inputs[j];
								if (!input.isHidden) {
									formFieldValues.push({
										label: window.GetLabel(field, input.id),
										value: 'gf_field:' + input.id,
									});
								}
							}
						} else {
							formFieldValues.push({
								label: window.GetLabel(field),
								value: 'gf_field:' + field.id,
							});
						}

					}

				}

				return formFieldValues;

			},
			operators: function () {

				/* Labels for operators are pulled from i18nStrings in the Vue bindings */
				if (this.filter.property in this.flattenedProperties) {
					var property = this.flattenedProperties[this.filter.property];

					if ('operators' in property) {
						return property.operators;
					}

					if ('group' in property) {
						var group = this.objectTypeInstance.groups[property.group];

						if ('operators' in group) {
							return group.operators;
						}
					}
				}

				return window.GPPA_ADMIN.defaultOperators;

			},
			filterPropertiesGrouped: function () {
				const groupedProperties: { [groupId: string]: any[] } = {...this.groupedProperties};

				for ( const [groupId, properties] of Object.entries(groupedProperties) ) {
					groupedProperties[groupId] = properties.filter(property => property?.['supports_filters'] !== false);

					if (groupedProperties[groupId].length === 0) {
						delete groupedProperties[groupId];
					}
				}

				return groupedProperties;
			},
			filterPropertiesUngrouped: function () {
				return this.ungroupedProperties?.filter((property: any) => property?.['supports_filters'] !== false);
			},
		},
	});
</script>
